#include <stdio.h>
#include <malloc.h>
#include "transport.h"
#include "client.h"

char string[] = //"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
               "  <xs:complexType name=\"openAttrs\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:anyType\">\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"annotated\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:openAttrs\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"id\" type=\"xs:ID\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:group name=\"schemaTop\">\n"
               "    <xs:choice>\n"
               "      <xs:group ref=\"xs:redefinable\"/>\n"
               "      <xs:element ref=\"xs:element\"/>\n"
               "      <xs:element ref=\"xs:attribute\"/>\n"
               "      <xs:element ref=\"xs:notation\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:group name=\"redefinable\">\n"
               "    <xs:choice>\n"
               "      <xs:element ref=\"xs:simpleType\"/>\n"
               "      <xs:element ref=\"xs:complexType\"/>\n"
               "      <xs:element ref=\"xs:group\"/>\n"
               "      <xs:element ref=\"xs:attributeGroup\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:simpleType name=\"formChoice\" vs:nonbrowsable=\"true\">\n"
               "    <xs:restriction base=\"xs:NMTOKEN\">\n"
               "      <xs:enumeration value=\"qualified\"/>\n"
               "      <xs:enumeration value=\"unqualified\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"reducedDerivationControl\" vs:nonbrowsable=\"true\">\n"
               "    <xs:restriction base=\"xs:derivationControl\">\n"
               "      <xs:enumeration value=\"extension\"/>\n"
               "      <xs:enumeration value=\"restriction\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"derivationSet\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union>\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:token\">\n"
               "          <xs:enumeration value=\"#all\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "      <xs:simpleType>\n"
               "        <xs:list itemType=\"xs:reducedDerivationControl\"/>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"typeDerivationControl\" vs:nonbrowsable=\"true\">\n"
               "    <xs:restriction base=\"xs:derivationControl\">\n"
               "      <xs:enumeration value=\"extension\"/>\n"
               "      <xs:enumeration value=\"restriction\"/>\n"
               "      <xs:enumeration value=\"list\"/>\n"
               "      <xs:enumeration value=\"union\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"fullDerivationSet\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union>\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:token\">\n"
               "          <xs:enumeration value=\"#all\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "      <xs:simpleType>\n"
               "        <xs:list itemType=\"xs:typeDerivationControl\"/>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:element name=\"schema\" id=\"schema\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-schema\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:openAttrs\">\n"
               "          <xs:sequence>\n"
               "            <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "              <xs:element ref=\"xs:include\"/>\n"
               "              <xs:element ref=\"xs:import\"/>\n"
               "              <xs:element ref=\"xs:redefine\"/>\n"
               "              <xs:element ref=\"xs:annotation\"/>\n"
               "            </xs:choice>\n"
               "            <xs:sequence minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "              <xs:group ref=\"xs:schemaTop\"/>\n"
               "              <xs:element ref=\"xs:annotation\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "            </xs:sequence>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"targetNamespace\" type=\"xs:anyURI\"/>\n"
               "          <xs:attribute name=\"version\" type=\"xs:token\"/>\n"
               "          <xs:attribute name=\"finalDefault\" type=\"xs:fullDerivationSet\" use=\"optional\" default=\"\"/>\n"
               "          <xs:attribute name=\"blockDefault\" type=\"xs:blockSet\" use=\"optional\" default=\"\"/>\n"
               "          <xs:attribute name=\"attributeFormDefault\" type=\"xs:formChoice\" use=\"optional\" default=\"unqualified\"/>\n"
               "          <xs:attribute name=\"elementFormDefault\" type=\"xs:formChoice\" use=\"optional\" default=\"unqualified\"/>\n"
               "          <xs:attribute name=\"id\" type=\"xs:ID\"/>\n"
               "          <xs:attribute ref=\"xml:lang\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "\n"
               "    <xs:key name=\"element\">\n"
               "      <xs:selector xpath=\"xs:element\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"attribute\">\n"
               "      <xs:selector xpath=\"xs:attribute\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"type\">\n"
               "      <xs:selector xpath=\"xs:complexType|xs:simpleType\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"group\">\n"
               "      <xs:selector xpath=\"xs:group\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"attributeGroup\">\n"
               "      <xs:selector xpath=\"xs:attributeGroup\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"notation\">\n"
               "      <xs:selector xpath=\"xs:notation\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "    <xs:key name=\"identityConstraint\">\n"
               "      <xs:selector xpath=\".//xs:key|.//xs:unique|.//xs:keyref\"/>\n"
               "      <xs:field xpath=\"@name\"/>\n"
               "    </xs:key>\n"
               "\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:simpleType name=\"allNNI\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union memberTypes=\"xs:nonNegativeInteger\">\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:NMTOKEN\">\n"
               "          <xs:enumeration value=\"unbounded\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:attributeGroup name=\"occurs\">\n"
               "    <xs:attribute name=\"minOccurs\" type=\"xs:nonNegativeInteger\" use=\"optional\" default=\"1\"/>\n"
               "    <xs:attribute name=\"maxOccurs\" type=\"xs:allNNI\" use=\"optional\" default=\"1\"/>\n"
               "  </xs:attributeGroup>\n"
               "\n"
               "  <xs:attributeGroup name=\"defRef\">\n"
               "    <xs:attribute name=\"name\" type=\"xs:NCName\" vs:snippet=\"yes\"/>\n"
               "    <xs:attribute name=\"ref\" type=\"xs:QName\"/>\n"
               "  </xs:attributeGroup>\n"
               "\n"
               "  <xs:group name=\"typeDefParticle\">\n"
               "    <xs:choice>\n"
               "      <xs:element name=\"group\" type=\"xs:groupRef\"/>\n"
               "      <xs:element ref=\"xs:all\"/>\n"
               "      <xs:element ref=\"xs:choice\"/>\n"
               "      <xs:element ref=\"xs:sequence\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "\n"
               "\n"
               "  <xs:group name=\"nestedParticle\">\n"
               "    <xs:choice>\n"
               "      <xs:element name=\"element\" type=\"xs:localElement\"/>\n"
               "      <xs:element name=\"group\" type=\"xs:groupRef\"/>\n"
               "      <xs:element ref=\"xs:choice\"/>\n"
               "      <xs:element ref=\"xs:sequence\"/>\n"
               "      <xs:element ref=\"xs:any\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:group name=\"particle\">\n"
               "    <xs:choice>\n"
               "      <xs:element name=\"element\" type=\"xs:localElement\"/>\n"
               "      <xs:element name=\"group\" type=\"xs:groupRef\"/>\n"
               "      <xs:element ref=\"xs:all\"/>\n"
               "      <xs:element ref=\"xs:choice\"/>\n"
               "      <xs:element ref=\"xs:sequence\"/>\n"
               "      <xs:element ref=\"xs:any\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:complexType name=\"attribute\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:sequence>\n"
               "          <xs:element name=\"simpleType\" minOccurs=\"0\" type=\"xs:localSimpleType\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attributeGroup ref=\"xs:defRef\"/>\n"
               "        <xs:attribute name=\"type\" type=\"xs:QName\"/>\n"
               "        <xs:attribute name=\"use\" use=\"optional\" default=\"optional\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:NMTOKEN\">\n"
               "              <xs:enumeration value=\"prohibited\"/>\n"
               "              <xs:enumeration value=\"optional\"/>\n"
               "              <xs:enumeration value=\"required\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "        <xs:attribute name=\"default\" type=\"xs:string\"/>\n"
               "        <xs:attribute name=\"fixed\" type=\"xs:string\"/>\n"
               "        <xs:attribute name=\"form\" type=\"xs:formChoice\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"topLevelAttribute\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:attribute\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:element name=\"simpleType\" minOccurs=\"0\" type=\"xs:localSimpleType\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"ref\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"form\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"use\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"name\" use=\"required\" type=\"xs:NCName\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:group name=\"attrDecls\">\n"
               "    <xs:sequence>\n"
               "      <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "        <xs:element name=\"attribute\" type=\"xs:attribute\"/>\n"
               "        <xs:element name=\"attributeGroup\" type=\"xs:attributeGroupRef\"/>\n"
               "      </xs:choice>\n"
               "      <xs:element ref=\"xs:anyAttribute\" minOccurs=\"0\"/>\n"
               "    </xs:sequence>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:element name=\"anyAttribute\" type=\"xs:wildcard\" id=\"anyAttribute\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-anyAttribute\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:group name=\"complexTypeModel\">\n"
               "    <xs:choice>\n"
               "      <xs:element ref=\"xs:simpleContent\" minOccurs=\"0\"/>\n"
               "      <xs:element ref=\"xs:complexContent\" minOccurs=\"0\"/>\n"
               "      <xs:sequence>\n"
               "        <xs:group ref=\"xs:typeDefParticle\" minOccurs=\"0\"/>\n"
               "        <xs:group ref=\"xs:attrDecls\"/>\n"
               "      </xs:sequence>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:complexType name=\"complexType\" abstract=\"true\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:group ref=\"xs:complexTypeModel\"/>\n"
               "        <xs:attribute name=\"name\" type=\"xs:NCName\"/>\n"
               "        <xs:attribute name=\"mixed\" type=\"xs:boolean\" use=\"optional\" default=\"false\">\n"
               "        </xs:attribute>\n"
               "        <xs:attribute name=\"abstract\" type=\"xs:boolean\" use=\"optional\" default=\"false\"/>\n"
               "        <xs:attribute name=\"final\" type=\"xs:derivationSet\"/>\n"
               "        <xs:attribute name=\"block\" type=\"xs:derivationSet\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"topLevelComplexType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:complexType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:complexTypeModel\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" type=\"xs:NCName\" use=\"required\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"localComplexType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:complexType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:complexTypeModel\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"abstract\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"final\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"block\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"restrictionType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:sequence>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:group ref=\"xs:typeDefParticle\"/>\n"
               "            <xs:group ref=\"xs:simpleRestrictionModel\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"base\" type=\"xs:QName\" use=\"required\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"complexRestrictionType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:restrictionType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:group ref=\"xs:typeDefParticle\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"extensionType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:sequence>\n"
               "          <xs:group ref=\"xs:typeDefParticle\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"base\" type=\"xs:QName\" use=\"required\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"complexContent\" id=\"complexContent\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-complexContent\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:choice>\n"
               "            <xs:element name=\"restriction\" type=\"xs:complexRestrictionType\"/>\n"
               "            <xs:element name=\"extension\" type=\"xs:extensionType\"/>\n"
               "          </xs:choice>\n"
               "          <xs:attribute name=\"mixed\" type=\"xs:boolean\">\n"
               "          </xs:attribute>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"simpleRestrictionType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:restrictionType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:group ref=\"xs:simpleRestrictionModel\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"simpleExtensionType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:extensionType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"simpleContent\" id=\"simpleContent\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-simpleContent\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:choice>\n"
               "            <xs:element name=\"restriction\" type=\"xs:simpleRestrictionType\"/>\n"
               "            <xs:element name=\"extension\" type=\"xs:simpleExtensionType\"/>\n"
               "          </xs:choice>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"complexType\" type=\"xs:topLevelComplexType\" id=\"complexType\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-complexType\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "\n"
               "  <xs:simpleType name=\"blockSet\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union>\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:token\">\n"
               "          <xs:enumeration value=\"#all\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "      <xs:simpleType>\n"
               "        <xs:list>\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:derivationControl\">\n"
               "              <xs:enumeration value=\"extension\"/>\n"
               "              <xs:enumeration value=\"restriction\"/>\n"
               "              <xs:enumeration value=\"substitution\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:list>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:complexType name=\"element\" abstract=\"true\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:sequence>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"/>\n"
               "            <xs:element name=\"complexType\" type=\"xs:localComplexType\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:identityConstraint\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attributeGroup ref=\"xs:defRef\"/>\n"
               "        <xs:attribute name=\"type\" type=\"xs:QName\"/>\n"
               "        <xs:attribute name=\"substitutionGroup\" type=\"xs:QName\"/>\n"
               "        <xs:attributeGroup ref=\"xs:occurs\"/>\n"
               "        <xs:attribute name=\"default\" type=\"xs:string\"/>\n"
               "        <xs:attribute name=\"fixed\" type=\"xs:string\"/>\n"
               "        <xs:attribute name=\"nillable\" type=\"xs:boolean\" use=\"optional\" default=\"false\"/>\n"
               "        <xs:attribute name=\"abstract\" type=\"xs:boolean\" use=\"optional\" default=\"false\"/>\n"
               "        <xs:attribute name=\"final\" type=\"xs:derivationSet\"/>\n"
               "        <xs:attribute name=\"block\" type=\"xs:blockSet\"/>\n"
               "        <xs:attribute name=\"form\" type=\"xs:formChoice\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"topLevelElement\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:element\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"/>\n"
               "            <xs:element name=\"complexType\" type=\"xs:localComplexType\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:identityConstraint\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"ref\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"form\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"minOccurs\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"maxOccurs\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"name\" use=\"required\" type=\"xs:NCName\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"localElement\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:element\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"/>\n"
               "            <xs:element name=\"complexType\" type=\"xs:localComplexType\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:identityConstraint\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"substitutionGroup\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"final\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"abstract\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"element\" type=\"xs:topLevelElement\" id=\"element\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-element\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"group\" abstract=\"true\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:group ref=\"xs:particle\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        <xs:attributeGroup ref=\"xs:defRef\"/>\n"
               "        <xs:attributeGroup ref=\"xs:occurs\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"realGroup\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:group\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\" maxOccurs=\"1\">\n"
               "            <xs:element ref=\"xs:all\"/>\n"
               "            <xs:element ref=\"xs:choice\"/>\n"
               "            <xs:element ref=\"xs:sequence\"/>\n"
               "          </xs:choice>\n"
               "        </xs:sequence>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"namedGroup\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:realGroup\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"1\" maxOccurs=\"1\">\n"
               "            <xs:element name=\"all\">\n"
               "              <xs:complexType>\n"
               "                <xs:complexContent>\n"
               "                  <xs:restriction base=\"xs:all\">\n"
               "                    <xs:group ref=\"xs:allModel\"/>\n"
               "                    <xs:attribute name=\"minOccurs\" use=\"prohibited\"/>\n"
               "                    <xs:attribute name=\"maxOccurs\" use=\"prohibited\"/>\n"
               "                    <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "                  </xs:restriction>\n"
               "                </xs:complexContent>\n"
               "              </xs:complexType>\n"
               "            </xs:element>\n"
               "            <xs:element name=\"choice\" type=\"xs:simpleExplicitGroup\"/>\n"
               "            <xs:element name=\"sequence\" type=\"xs:simpleExplicitGroup\"/>\n"
               "          </xs:choice>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" use=\"required\" type=\"xs:NCName\"/>\n"
               "        <xs:attribute name=\"ref\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"minOccurs\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"maxOccurs\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"groupRef\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:realGroup\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"ref\" use=\"required\" type=\"xs:QName\"/>\n"
               "        <xs:attribute name=\"name\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"explicitGroup\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:group\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:nestedParticle\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" type=\"xs:NCName\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"ref\" type=\"xs:QName\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"simpleExplicitGroup\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:explicitGroup\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:nestedParticle\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"minOccurs\" use=\"prohibited\"/>\n"
               "        <xs:attribute name=\"maxOccurs\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:group name=\"allModel\">\n"
               "    <xs:sequence>\n"
               "      <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "      <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "        <xs:element name=\"element\" type=\"xs:narrowMaxMin\"/>\n"
               "      </xs:choice>\n"
               "    </xs:sequence>\n"
               "  </xs:group>\n"
               "\n"
               "\n"
               "  <xs:complexType name=\"narrowMaxMin\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:localElement\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:choice minOccurs=\"0\">\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"/>\n"
               "            <xs:element name=\"complexType\" type=\"xs:localComplexType\"/>\n"
               "          </xs:choice>\n"
               "          <xs:group ref=\"xs:identityConstraint\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"minOccurs\" use=\"optional\" default=\"1\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:nonNegativeInteger\">\n"
               "              <xs:enumeration value=\"0\"/>\n"
               "              <xs:enumeration value=\"1\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "        <xs:attribute name=\"maxOccurs\" use=\"optional\" default=\"1\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:allNNI\">\n"
               "              <xs:enumeration value=\"0\"/>\n"
               "              <xs:enumeration value=\"1\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"all\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:explicitGroup\">\n"
               "        <xs:group ref=\"xs:allModel\"/>\n"
               "        <xs:attribute name=\"minOccurs\" use=\"optional\" default=\"1\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:nonNegativeInteger\">\n"
               "              <xs:enumeration value=\"0\"/>\n"
               "              <xs:enumeration value=\"1\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "        <xs:attribute name=\"maxOccurs\" use=\"optional\" default=\"1\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:allNNI\">\n"
               "              <xs:enumeration value=\"1\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"all\" id=\"all\" type=\"xs:all\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-all\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"choice\" type=\"xs:explicitGroup\" id=\"choice\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-choice\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"sequence\" type=\"xs:explicitGroup\" id=\"sequence\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-sequence\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"group\" type=\"xs:namedGroup\" id=\"group\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-group\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"wildcard\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:attribute name=\"namespace\" type=\"xs:namespaceList\" use=\"optional\" default=\"##any\"/>\n"
               "        <xs:attribute name=\"processContents\" use=\"optional\" default=\"strict\">\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:NMTOKEN\">\n"
               "              <xs:enumeration value=\"skip\"/>\n"
               "              <xs:enumeration value=\"lax\"/>\n"
               "              <xs:enumeration value=\"strict\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:attribute>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"any\" id=\"any\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-any\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:wildcard\">\n"
               "          <xs:attributeGroup ref=\"xs:occurs\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:simpleType name=\"namespaceList\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union>\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:token\">\n"
               "          <xs:enumeration value=\"##any\"/>\n"
               "          <xs:enumeration value=\"##other\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "      <xs:simpleType>\n"
               "        <xs:list>\n"
               "          <xs:simpleType>\n"
               "            <xs:union memberTypes=\"xs:anyURI\">\n"
               "              <xs:simpleType>\n"
               "                <xs:restriction base=\"xs:token\">\n"
               "                  <xs:enumeration value=\"##targetNamespace\"/>\n"
               "                  <xs:enumeration value=\"##local\"/>\n"
               "                </xs:restriction>\n"
               "              </xs:simpleType>\n"
               "            </xs:union>\n"
               "          </xs:simpleType>\n"
               "        </xs:list>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:element name=\"attribute\" type=\"xs:topLevelAttribute\" id=\"attribute\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-attribute\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"attributeGroup\" abstract=\"true\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:group ref=\"xs:attrDecls\"/>\n"
               "        <xs:attributeGroup ref=\"xs:defRef\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"namedAttributeGroup\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:attributeGroup\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:attrDecls\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" use=\"required\" type=\"xs:NCName\"/>\n"
               "        <xs:attribute name=\"ref\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"attributeGroupRef\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:attributeGroup\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"ref\" use=\"required\" type=\"xs:QName\"/>\n"
               "        <xs:attribute name=\"name\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"attributeGroup\" type=\"xs:namedAttributeGroup\" id=\"attributeGroup\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-attributeGroup\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"include\" id=\"include\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-include\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:attribute name=\"schemaLocation\" type=\"xs:anyURI\" use=\"required\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"redefine\" id=\"redefine\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-redefine\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:openAttrs\">\n"
               "          <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "            <xs:element ref=\"xs:annotation\"/>\n"
               "            <xs:group ref=\"xs:redefinable\"/>\n"
               "          </xs:choice>\n"
               "          <xs:attribute name=\"schemaLocation\" type=\"xs:anyURI\" use=\"required\"/>\n"
               "          <xs:attribute name=\"id\" type=\"xs:ID\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"import\" id=\"import\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-import\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:attribute name=\"namespace\" type=\"xs:anyURI\"/>\n"
               "          <xs:attribute name=\"schemaLocation\" type=\"xs:anyURI\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"selector\" id=\"selector\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-selector\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:attribute name=\"xpath\" use=\"required\" type=\"xs:string\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"field\" id=\"field\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-field\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:attribute name=\"xpath\" use=\"required\" type=\"xs:string\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"keybase\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:selector\"/>\n"
               "          <xs:element ref=\"xs:field\" minOccurs=\"1\" maxOccurs=\"unbounded\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" type=\"xs:NCName\" use=\"required\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:group name=\"identityConstraint\">\n"
               "    <xs:choice>\n"
               "      <xs:element ref=\"xs:unique\"/>\n"
               "      <xs:element ref=\"xs:key\"/>\n"
               "      <xs:element ref=\"xs:keyref\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:element name=\"unique\" type=\"xs:keybase\" id=\"unique\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-unique\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"key\" type=\"xs:keybase\" id=\"key\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-key\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"keyref\" id=\"keyref\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-keyref\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:keybase\">\n"
               "          <xs:attribute name=\"refer\" type=\"xs:QName\" use=\"required\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"notation\" id=\"notation\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-notation\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:attribute name=\"name\" type=\"xs:NCName\" use=\"required\"/>\n"
               "          <xs:attribute name=\"public\" type=\"xs:public\"/>\n"
               "          <xs:attribute name=\"system\" type=\"xs:anyURI\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:simpleType name=\"public\" vs:nonbrowsable=\"true\">\n"
               "    <xs:restriction base=\"xs:token\"/>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:element name=\"appinfo\" id=\"appinfo\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-appinfo\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType mixed=\"true\">\n"
               "      <xs:sequence minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "        <xs:any processContents=\"lax\"/>\n"
               "      </xs:sequence>\n"
               "      <xs:attribute name=\"source\" type=\"xs:anyURI\"/>\n"
               "      <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"documentation\" id=\"documentation\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-documentation\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType mixed=\"true\">\n"
               "      <xs:sequence minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "        <xs:any processContents=\"lax\"/>\n"
               "      </xs:sequence>\n"
               "      <xs:attribute name=\"source\" type=\"xs:anyURI\"/>\n"
               "      <xs:attribute ref=\"xml:lang\"/>\n"
               "      <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"annotation\" id=\"annotation\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-1/#element-annotation\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:openAttrs\">\n"
               "          <xs:choice minOccurs=\"0\" maxOccurs=\"unbounded\">\n"
               "            <xs:element ref=\"xs:appinfo\"/>\n"
               "            <xs:element ref=\"xs:documentation\"/>\n"
               "          </xs:choice>\n"
               "          <xs:attribute name=\"id\" type=\"xs:ID\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:notation name=\"XMLSchemaStructures\" public=\"structures\" system=\"http://www.w3.org/2000/08/XMLSchema.xsd\"/>\n"
               "  <xs:notation name=\"XML\" public=\"REC-xml-19980210\" system=\"http://www.w3.org/TR/1998/REC-xml-19980210\"/>\n"
               "\n"
               "  <xs:complexType name=\"anyType\" mixed=\"true\">\n"
               "    <xs:sequence>\n"
               "      <xs:any minOccurs=\"0\" maxOccurs=\"unbounded\" processContents=\"lax\"/>\n"
               "    </xs:sequence>\n"
               "    <xs:anyAttribute processContents=\"lax\"/>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:simpleType name=\"string\" id=\"string\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#string\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"preserve\" id=\"string.preserve\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"boolean\" id=\"boolean\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#boolean\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\" fixed=\"true\"\n"
               "        id=\"boolean.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"float\" id=\"float\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#float\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\" fixed=\"true\"\n"
               "        id=\"float.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"double\" id=\"double\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#double\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"double.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"decimal\" id=\"decimal\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#decimal\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"decimal.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"duration\" id=\"duration\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#duration\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"duration.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"dateTime\" id=\"dateTime\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#dateTime\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"dateTime.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"time\" id=\"time\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#time\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"time.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"date\" id=\"date\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#date\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"date.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"gYearMonth\" id=\"gYearMonth\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#gYearMonth\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"gYearMonth.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"gYear\" id=\"gYear\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#gYear\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"gYear.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"gMonthDay\" id=\"gMonthDay\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#gMonthDay\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\" fixed=\"true\"\n"
               "             id=\"gMonthDay.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"gDay\" id=\"gDay\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#gDay\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "             id=\"gDay.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"gMonth\" id=\"gMonth\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#gMonth\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "             id=\"gMonth.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"hexBinary\" id=\"hexBinary\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#binary\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\" fixed=\"true\"\n"
               "        id=\"hexBinary.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"base64Binary\" id=\"base64Binary\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#base64Binary\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\" fixed=\"true\"\n"
               "        id=\"base64Binary.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"anyURI\" id=\"anyURI\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#anyURI\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"anyURI.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"QName\" id=\"QName\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#QName\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"QName.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"NOTATION\" id=\"NOTATION\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#NOTATION\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:anySimpleType\">\n"
               "      <xs:whiteSpace value=\"collapse\"  fixed=\"true\"\n"
               "        id=\"NOTATION.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"normalizedString\" id=\"normalizedString\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#normalizedString\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:string\">\n"
               "      <xs:whiteSpace value=\"replace\"\n"
               "        id=\"normalizedString.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"token\" id=\"token\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#token\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:normalizedString\">\n"
               "      <xs:whiteSpace value=\"collapse\" id=\"token.whiteSpace\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"language\" id=\"language\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#language\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:token\">\n"
               "      <xs:pattern value=\"[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*\"\n"
               "                id=\"language.pattern\">\n"
               "      </xs:pattern>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"IDREFS\" id=\"IDREFS\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#IDREFS\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction>\n"
               "      <xs:simpleType>\n"
               "        <xs:list itemType=\"xs:IDREF\"/>\n"
               "      </xs:simpleType>\n"
               "      <xs:minLength value=\"1\" id=\"IDREFS.minLength\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"ENTITIES\" id=\"ENTITIES\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#ENTITIES\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction>\n"
               "      <xs:simpleType>\n"
               "        <xs:list itemType=\"xs:ENTITY\"/>\n"
               "      </xs:simpleType>\n"
               "      <xs:minLength value=\"1\" id=\"ENTITIES.minLength\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"NMTOKEN\" id=\"NMTOKEN\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#NMTOKEN\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:token\">\n"
               "      <xs:pattern value=\"\\c+\" id=\"NMTOKEN.pattern\">\n"
               "      </xs:pattern>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"NMTOKENS\" id=\"NMTOKENS\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#NMTOKENS\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction>\n"
               "      <xs:simpleType>\n"
               "        <xs:list itemType=\"xs:NMTOKEN\"/>\n"
               "      </xs:simpleType>\n"
               "      <xs:minLength value=\"1\" id=\"NMTOKENS.minLength\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"Name\" id=\"Name\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#Name\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:token\">\n"
               "      <xs:pattern value=\"\\i\\c*\" id=\"Name.pattern\">\n"
               "      </xs:pattern>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"NCName\" id=\"NCName\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#NCName\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:Name\">\n"
               "      <xs:pattern value=\"[\\i-[:]][\\c-[:]]*\" id=\"NCName.pattern\">\n"
               "      </xs:pattern>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"ID\" id=\"ID\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#ID\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:NCName\"/>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"IDREF\" id=\"IDREF\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#IDREF\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:NCName\"/>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"ENTITY\" id=\"ENTITY\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#ENTITY\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:NCName\"/>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"integer\" id=\"integer\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#integer\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:decimal\">\n"
               "      <xs:fractionDigits value=\"0\" fixed=\"true\" id=\"integer.fractionDigits\"/>\n"
               "      <xs:pattern value=\"[\\-+]?[0-9]+\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"nonPositiveInteger\" id=\"nonPositiveInteger\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#nonPositiveInteger\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:integer\">\n"
               "      <xs:maxInclusive value=\"0\" id=\"nonPositiveInteger.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"negativeInteger\" id=\"negativeInteger\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#negativeInteger\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:nonPositiveInteger\">\n"
               "      <xs:maxInclusive value=\"-1\" id=\"negativeInteger.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"long\" id=\"long\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#long\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:integer\">\n"
               "      <xs:minInclusive value=\"-9223372036854775808\" id=\"long.minInclusive\"/>\n"
               "      <xs:maxInclusive value=\"9223372036854775807\" id=\"long.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"int\" id=\"int\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#int\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:long\">\n"
               "      <xs:minInclusive value=\"-2147483648\" id=\"int.minInclusive\"/>\n"
               "      <xs:maxInclusive value=\"2147483647\" id=\"int.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"short\" id=\"short\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#short\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:int\">\n"
               "      <xs:minInclusive value=\"-32768\" id=\"short.minInclusive\"/>\n"
               "      <xs:maxInclusive value=\"32767\" id=\"short.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"byte\" id=\"byte\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#byte\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:short\">\n"
               "      <xs:minInclusive value=\"-128\" id=\"byte.minInclusive\"/>\n"
               "      <xs:maxInclusive value=\"127\" id=\"byte.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"nonNegativeInteger\" id=\"nonNegativeInteger\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#nonNegativeInteger\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:integer\">\n"
               "      <xs:minInclusive value=\"0\" id=\"nonNegativeInteger.minInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"unsignedLong\" id=\"unsignedLong\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#unsignedLong\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
               "      <xs:maxInclusive value=\"18446744073709551615\"\n"
               "        id=\"unsignedLong.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"unsignedInt\" id=\"unsignedInt\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#unsignedInt\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:unsignedLong\">\n"
               "      <xs:maxInclusive value=\"4294967295\"\n"
               "        id=\"unsignedInt.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"unsignedShort\" id=\"unsignedShort\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#unsignedShort\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:unsignedInt\">\n"
               "      <xs:maxInclusive value=\"65535\"\n"
               "        id=\"unsignedShort.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"unsignedByte\" id=\"unsignedByte\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#unsignedByte\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:unsignedShort\">\n"
               "      <xs:maxInclusive value=\"255\" id=\"unsignedByte.maxInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"positiveInteger\" id=\"positiveInteger\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#positiveInteger\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:restriction base=\"xs:nonNegativeInteger\">\n"
               "      <xs:minInclusive value=\"1\" id=\"positiveInteger.minInclusive\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:simpleType name=\"derivationControl\" vs:nonbrowsable=\"true\">\n"
               "    <xs:restriction base=\"xs:NMTOKEN\">\n"
               "      <xs:enumeration value=\"substitution\"/>\n"
               "      <xs:enumeration value=\"extension\"/>\n"
               "      <xs:enumeration value=\"restriction\"/>\n"
               "      <xs:enumeration value=\"list\"/>\n"
               "      <xs:enumeration value=\"union\"/>\n"
               "    </xs:restriction>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:group name=\"simpleDerivation\">\n"
               "    <xs:choice>\n"
               "      <xs:element ref=\"xs:restriction\"/>\n"
               "      <xs:element ref=\"xs:list\"/>\n"
               "      <xs:element ref=\"xs:union\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:simpleType name=\"simpleDerivationSet\" vs:nonbrowsable=\"true\">\n"
               "    <xs:union>\n"
               "      <xs:simpleType>\n"
               "        <xs:restriction base=\"xs:token\">\n"
               "          <xs:enumeration value=\"#all\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:simpleType>\n"
               "      <xs:simpleType>\n"
               "        <xs:list>\n"
               "          <xs:simpleType>\n"
               "            <xs:restriction base=\"xs:derivationControl\">\n"
               "              <xs:enumeration value=\"list\"/>\n"
               "              <xs:enumeration value=\"union\"/>\n"
               "              <xs:enumeration value=\"restriction\"/>\n"
               "            </xs:restriction>\n"
               "          </xs:simpleType>\n"
               "        </xs:list>\n"
               "      </xs:simpleType>\n"
               "    </xs:union>\n"
               "  </xs:simpleType>\n"
               "\n"
               "  <xs:complexType name=\"simpleType\" abstract=\"true\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:group ref=\"xs:simpleDerivation\"/>\n"
               "        <xs:attribute name=\"final\" type=\"xs:simpleDerivationSet\"/>\n"
               "        <xs:attribute name=\"name\" type=\"xs:NCName\">\n"
               "        </xs:attribute>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"topLevelSimpleType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:simpleType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:simpleDerivation\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" use=\"required\"\n"
               "             type=\"xs:NCName\">\n"
               "        </xs:attribute>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"localSimpleType\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:simpleType\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          <xs:group ref=\"xs:simpleDerivation\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"name\" use=\"prohibited\">\n"
               "        </xs:attribute>\n"
               "        <xs:attribute name=\"final\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"simpleType\" type=\"xs:topLevelSimpleType\" id=\"simpleType\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-simpleType\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:group name=\"facets\">\n"
               "    <xs:choice>\n"
               "      <xs:element ref=\"xs:minExclusive\"/>\n"
               "      <xs:element ref=\"xs:minInclusive\"/>\n"
               "      <xs:element ref=\"xs:maxExclusive\"/>\n"
               "      <xs:element ref=\"xs:maxInclusive\"/>\n"
               "      <xs:element ref=\"xs:totalDigits\"/>\n"
               "      <xs:element ref=\"xs:fractionDigits\"/>\n"
               "      <xs:element ref=\"xs:length\"/>\n"
               "      <xs:element ref=\"xs:minLength\"/>\n"
               "      <xs:element ref=\"xs:maxLength\"/>\n"
               "      <xs:element ref=\"xs:enumeration\"/>\n"
               "      <xs:element ref=\"xs:whiteSpace\"/>\n"
               "      <xs:element ref=\"xs:pattern\"/>\n"
               "    </xs:choice>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:group name=\"simpleRestrictionModel\">\n"
               "    <xs:sequence>\n"
               "      <xs:element name=\"simpleType\" type=\"xs:localSimpleType\" minOccurs=\"0\"/>\n"
               "      <xs:group ref=\"xs:facets\" minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "    </xs:sequence>\n"
               "  </xs:group>\n"
               "\n"
               "  <xs:element name=\"restriction\" id=\"restriction\">\n"
               "    <xs:complexType>\n"
               "      <xs:annotation>\n"
               "        <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-restriction\"/>\n"
               "      </xs:annotation>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:group ref=\"xs:simpleRestrictionModel\"/>\n"
               "          <xs:attribute name=\"base\" type=\"xs:QName\" use=\"optional\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"list\" id=\"list\">\n"
               "    <xs:complexType>\n"
               "      <xs:annotation>\n"
               "        <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-list\"/>\n"
               "      </xs:annotation>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:sequence>\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"\n"
               "                minOccurs=\"0\"/>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"itemType\" type=\"xs:QName\" use=\"optional\"/>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"union\" id=\"union\">\n"
               "    <xs:complexType>\n"
               "      <xs:annotation>\n"
               "        <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-union\"/>\n"
               "      </xs:annotation>\n"
               "      <xs:complexContent>\n"
               "        <xs:extension base=\"xs:annotated\">\n"
               "          <xs:sequence>\n"
               "            <xs:element name=\"simpleType\" type=\"xs:localSimpleType\"\n"
               "                minOccurs=\"0\" maxOccurs=\"unbounded\"/>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"memberTypes\" use=\"optional\">\n"
               "            <xs:simpleType>\n"
               "              <xs:list itemType=\"xs:QName\"/>\n"
               "            </xs:simpleType>\n"
               "          </xs:attribute>\n"
               "        </xs:extension>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"facet\">\n"
               "    <xs:complexContent>\n"
               "      <xs:extension base=\"xs:annotated\">\n"
               "        <xs:attribute name=\"value\" use=\"required\"/>\n"
               "        <xs:attribute name=\"fixed\" type=\"xs:boolean\" use=\"optional\"\n"
               "                      default=\"false\"/>\n"
               "      </xs:extension>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:complexType name=\"noFixedFacet\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:facet\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"fixed\" use=\"prohibited\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"minExclusive\" id=\"minExclusive\" type=\"xs:facet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-minExclusive\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"minInclusive\" id=\"minInclusive\" type=\"xs:facet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-minInclusive\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"maxExclusive\" id=\"maxExclusive\" type=\"xs:facet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-maxExclusive\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"maxInclusive\" id=\"maxInclusive\" type=\"xs:facet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-maxInclusive\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:complexType name=\"numFacet\">\n"
               "    <xs:complexContent>\n"
               "      <xs:restriction base=\"xs:facet\">\n"
               "        <xs:sequence>\n"
               "          <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "        </xs:sequence>\n"
               "        <xs:attribute name=\"value\" type=\"xs:nonNegativeInteger\" use=\"required\"/>\n"
               "        <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "      </xs:restriction>\n"
               "    </xs:complexContent>\n"
               "  </xs:complexType>\n"
               "\n"
               "  <xs:element name=\"totalDigits\" id=\"totalDigits\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-totalDigits\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:restriction base=\"xs:numFacet\">\n"
               "          <xs:sequence>\n"
               "            <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"value\" type=\"xs:positiveInteger\" use=\"required\"/>\n"
               "          <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"fractionDigits\" id=\"fractionDigits\" type=\"xs:numFacet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-fractionDigits\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"length\" id=\"length\" type=\"xs:numFacet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-length\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"minLength\" id=\"minLength\" type=\"xs:numFacet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-minLength\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "  <xs:element name=\"maxLength\" id=\"maxLength\" type=\"xs:numFacet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-maxLength\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"enumeration\" id=\"enumeration\" type=\"xs:noFixedFacet\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-enumeration\"/>\n"
               "    </xs:annotation>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"whiteSpace\" id=\"whiteSpace\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-whiteSpace\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:restriction base=\"xs:facet\">\n"
               "          <xs:sequence>\n"
               "            <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"value\" use=\"required\">\n"
               "            <xs:simpleType>\n"
               "              <xs:restriction base=\"xs:NMTOKEN\">\n"
               "                <xs:enumeration value=\"preserve\"/>\n"
               "                <xs:enumeration value=\"replace\"/>\n"
               "                <xs:enumeration value=\"collapse\"/>\n"
               "              </xs:restriction>\n"
               "            </xs:simpleType>\n"
               "          </xs:attribute>\n"
               "          <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "  <xs:element name=\"pattern\" id=\"pattern\">\n"
               "    <xs:annotation>\n"
               "      <xs:documentation source=\"http://www.w3.org/TR/xmlschema-2/#element-pattern\"/>\n"
               "    </xs:annotation>\n"
               "    <xs:complexType>\n"
               "      <xs:complexContent>\n"
               "        <xs:restriction base=\"xs:noFixedFacet\">\n"
               "          <xs:sequence>\n"
               "            <xs:element ref=\"xs:annotation\" minOccurs=\"0\"/>\n"
               "          </xs:sequence>\n"
               "          <xs:attribute name=\"value\" type=\"xs:string\" use=\"required\"/>\n"
               "          <xs:anyAttribute namespace=\"##other\" processContents=\"lax\"/>\n"
               "        </xs:restriction>\n"
               "      </xs:complexContent>\n"
               "    </xs:complexType>\n"
               "  </xs:element>\n"
               "\n"
               "</xs:schema>";

struct link{
    struct link* parent;
    int value;
};

int q = 1;

void parse(){
    int j=0;
    int level=0;
    struct link* fn = &(struct link){0,6};
    for(int i=0; i<2707/*2716*/; i++){
        char que[MAX]={0};
        int ind=0;
        if(string[j]=='\n'){
            j++;
            continue;
        }
        int copyJ = j;
        while(string[copyJ++]!='<');
        if(string[copyJ]=='/'){
            while(string[j++]!='\n');
            continue;
        }
        int counter = 0;
        while(string[j++]==' '){
            counter++;
            //printf(" ");
        }
        counter/=2;
        j--;
        int value = 0;
        if(counter<level){
            value = ++q;
            while(counter!=level){
                level--;
                struct link* copy = fn;
                fn=fn->parent;
                free(copy);
            }
            fn->value=i;
        }
        if(counter>level){
            level++;
            struct link* copy = malloc(sizeof(struct link));
            copy->parent=fn;
            copy->value=i;
            fn=copy;
        }
        int result = fn->parent->value;
        while(string[j]!='>')
            if(string[j]!=' ')
                que[ind++]=string[j++];
                //printf("%c", string[j++]);
            else
                j++;
        j++;
        que[ind++]='>';
        if((int)(que[0])!=0){
            if(i==334){
                printf("123");
            }

            int ret = func(que, ind, fn->parent->value, value);
            fn->value=ret;
        }

        //printf("> %d %d\n", i, result);
    }
}